export const APP_MEDIA_RETRIEVED = "APP_MEDIA_RETRIEVED";
export const APP_INITTIAL_DATA_RETRIEVED = "APP_INITTIAL_DATA_RETRIEVED";
export const APP_UPDATE_CONTENT_LIST = "APP_UPDATE_CONTENT_LIST";
export const APP_MEDIA_UPLOAD_FAILED = "APP_MEDIA_UPLOAD_FAILED";
export const APP_MEDIA_UPLOAD_SUCCESSFULLY = "APP_MEDIA_UPLOAD_SUCCESSFULLY";